#
# Referral Rock
# This Postman collection provides a sample of a call to each of the Referral Rock API endpoints.
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'ReferralRockPS' -name 'ReferralRockReferralRockDefaultApi' {
    Context 'Invoke-ReferralRockApiEmailGetunsubscribedGet' {
        It 'Test Invoke-ReferralRockApiEmailGetunsubscribedGet' {
            #$TestResult = Invoke-ReferralRockApiEmailGetunsubscribedGet -Authorization "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ReferralRockApiEmailRemoveunsubscribePost' {
        It 'Test Invoke-ReferralRockApiEmailRemoveunsubscribePost' {
            #$TestResult = Invoke-ReferralRockApiEmailRemoveunsubscribePost -Authorization "TEST_VALUE" -ContentType "TEST_VALUE" -Body "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ReferralRockApiEmailUnsubscribePost' {
        It 'Test Invoke-ReferralRockApiEmailUnsubscribePost' {
            #$TestResult = Invoke-ReferralRockApiEmailUnsubscribePost -ContentType "TEST_VALUE" -Authorization "TEST_VALUE" -Body "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ReferralRockApiEventPost' {
        It 'Test Invoke-ReferralRockApiEventPost' {
            #$TestResult = Invoke-ReferralRockApiEventPost -Authorization "TEST_VALUE" -ContentType "TEST_VALUE" -Body "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ReferralRockApiHooksDelete' {
        It 'Test Invoke-ReferralRockApiHooksDelete' {
            #$TestResult = Invoke-ReferralRockApiHooksDelete -ContentType "TEST_VALUE" -Authorization "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ReferralRockApiHooksHistoryEventNameGet' {
        It 'Test Invoke-ReferralRockApiHooksHistoryEventNameGet' {
            #$TestResult = Invoke-ReferralRockApiHooksHistoryEventNameGet -EventName "TEST_VALUE" -Authorization "TEST_VALUE" -ContentType "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ReferralRockApiHooksPost' {
        It 'Test Invoke-ReferralRockApiHooksPost' {
            #$TestResult = Invoke-ReferralRockApiHooksPost -Authorization "TEST_VALUE" -ContentType "TEST_VALUE" -Body "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ReferralRockApiInvitefeedPost' {
        It 'Test Invoke-ReferralRockApiInvitefeedPost' {
            #$TestResult = Invoke-ReferralRockApiInvitefeedPost -Authorization "TEST_VALUE" -ContentType "TEST_VALUE" -Body "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ReferralRockApiInvitefeedsPost' {
        It 'Test Invoke-ReferralRockApiInvitefeedsPost' {
            #$TestResult = Invoke-ReferralRockApiInvitefeedsPost -Authorization "TEST_VALUE" -ContentType "TEST_VALUE" -Body "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ReferralRockApiMemberaccessPost' {
        It 'Test Invoke-ReferralRockApiMemberaccessPost' {
            #$TestResult = Invoke-ReferralRockApiMemberaccessPost -Authorization "TEST_VALUE" -ContentType "TEST_VALUE" -Body "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ReferralRockApiMemberaccessurlsPost' {
        It 'Test Invoke-ReferralRockApiMemberaccessurlsPost' {
            #$TestResult = Invoke-ReferralRockApiMemberaccessurlsPost -Authorization "TEST_VALUE" -ContentType "TEST_VALUE" -Body "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ReferralRockApiMembersGet' {
        It 'Test Invoke-ReferralRockApiMembersGet' {
            #$TestResult = Invoke-ReferralRockApiMembersGet -Authorization "TEST_VALUE" -ProgramId "TEST_VALUE" -Query "TEST_VALUE" -ShowDisabled "TEST_VALUE" -Sort "TEST_VALUE" -DateFrom "TEST_VALUE" -DateTo "TEST_VALUE" -Offset "TEST_VALUE" -Count "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ReferralRockApiMembersPost' {
        It 'Test Invoke-ReferralRockApiMembersPost' {
            #$TestResult = Invoke-ReferralRockApiMembersPost -ContentType "TEST_VALUE" -Authorization "TEST_VALUE" -Body "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ReferralRockApiMembersRemovePost' {
        It 'Test Invoke-ReferralRockApiMembersRemovePost' {
            #$TestResult = Invoke-ReferralRockApiMembersRemovePost -Authorization "TEST_VALUE" -ContentType "TEST_VALUE" -Body "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ReferralRockApiMembersUpdatePost' {
        It 'Test Invoke-ReferralRockApiMembersUpdatePost' {
            #$TestResult = Invoke-ReferralRockApiMembersUpdatePost -Authorization "TEST_VALUE" -ContentType "TEST_VALUE" -Body "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ReferralRockApiPayoutsAddPost' {
        It 'Test Invoke-ReferralRockApiPayoutsAddPost' {
            #$TestResult = Invoke-ReferralRockApiPayoutsAddPost -Authorization "TEST_VALUE" -ContentType "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ReferralRockApiPayoutsPayoutIdGet' {
        It 'Test Invoke-ReferralRockApiPayoutsPayoutIdGet' {
            #$TestResult = Invoke-ReferralRockApiPayoutsPayoutIdGet -PayoutId "TEST_VALUE" -Authorization "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ReferralRockApiPayoutsPendingGet' {
        It 'Test Invoke-ReferralRockApiPayoutsPendingGet' {
            #$TestResult = Invoke-ReferralRockApiPayoutsPendingGet -Authorization "TEST_VALUE" -MemberId "TEST_VALUE" -RecipientId "TEST_VALUE" -IncludeIneligible "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ReferralRockApiPayoutsTransactionsGet' {
        It 'Test Invoke-ReferralRockApiPayoutsTransactionsGet' {
            #$TestResult = Invoke-ReferralRockApiPayoutsTransactionsGet -Authorization "TEST_VALUE" -RecipientId "TEST_VALUE" -TransactionId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ReferralRockApiPayoutsTransactionsPost' {
        It 'Test Invoke-ReferralRockApiPayoutsTransactionsPost' {
            #$TestResult = Invoke-ReferralRockApiPayoutsTransactionsPost -Authorization "TEST_VALUE" -ContentType "TEST_VALUE" -OverrideIneligible "TEST_VALUE" -Body "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ReferralRockApiProgramCreatePost' {
        It 'Test Invoke-ReferralRockApiProgramCreatePost' {
            #$TestResult = Invoke-ReferralRockApiProgramCreatePost -Authorization "TEST_VALUE" -ContentType "TEST_VALUE" -ProgramName "TEST_VALUE" -ProgramTitle "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ReferralRockApiProgramGetsingleGet' {
        It 'Test Invoke-ReferralRockApiProgramGetsingleGet' {
            #$TestResult = Invoke-ReferralRockApiProgramGetsingleGet -Authorization "TEST_VALUE" -ProgramName "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ReferralRockApiProgramsGet' {
        It 'Test Invoke-ReferralRockApiProgramsGet' {
            #$TestResult = Invoke-ReferralRockApiProgramsGet -Authorization "TEST_VALUE" -Offset "TEST_VALUE" -Count "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ReferralRockApiReferralRemovePost' {
        It 'Test Invoke-ReferralRockApiReferralRemovePost' {
            #$TestResult = Invoke-ReferralRockApiReferralRemovePost -Authorization "TEST_VALUE" -ContentType "TEST_VALUE" -Body "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ReferralRockApiReferralSingleGet' {
        It 'Test Invoke-ReferralRockApiReferralSingleGet' {
            #$TestResult = Invoke-ReferralRockApiReferralSingleGet -Authorization "TEST_VALUE" -ContentType "TEST_VALUE" -ReferralId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ReferralRockApiReferralUpdatePost' {
        It 'Test Invoke-ReferralRockApiReferralUpdatePost' {
            #$TestResult = Invoke-ReferralRockApiReferralUpdatePost -Authorization "TEST_VALUE" -ContentType "TEST_VALUE" -Body "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ReferralRockApiReferralsGet' {
        It 'Test Invoke-ReferralRockApiReferralsGet' {
            #$TestResult = Invoke-ReferralRockApiReferralsGet -Authorization "TEST_VALUE" -ProgramId "TEST_VALUE" -Query "TEST_VALUE" -MemberId "TEST_VALUE" -Sort "TEST_VALUE" -DateFrom "TEST_VALUE" -DateTo "TEST_VALUE" -Status "TEST_VALUE" -Offset "TEST_VALUE" -Count "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ReferralRockApiReferralsPost' {
        It 'Test Invoke-ReferralRockApiReferralsPost' {
            #$TestResult = Invoke-ReferralRockApiReferralsPost -ContentType "TEST_VALUE" -Authorization "TEST_VALUE" -Body "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ReferralRockApiReferralsStatusPost' {
        It 'Test Invoke-ReferralRockApiReferralsStatusPost' {
            #$TestResult = Invoke-ReferralRockApiReferralsStatusPost -ContentType "TEST_VALUE" -Authorization "TEST_VALUE" -Body "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ReferralRockApiRewardrulesGet' {
        It 'Test Invoke-ReferralRockApiRewardrulesGet' {
            #$TestResult = Invoke-ReferralRockApiRewardrulesGet -Authorization "TEST_VALUE" -ProgramId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ReferralRockApiRewardsGet' {
        It 'Test Invoke-ReferralRockApiRewardsGet' {
            #$TestResult = Invoke-ReferralRockApiRewardsGet -Authorization "TEST_VALUE" -ProgramId "TEST_VALUE" -MemberId "TEST_VALUE" -Query "TEST_VALUE" -Status "TEST_VALUE" -Sort "TEST_VALUE" -DateFrom "TEST_VALUE" -DateTo "TEST_VALUE" -Offset "TEST_VALUE" -Count "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ReferralRockApiRewardsIssuePost' {
        It 'Test Invoke-ReferralRockApiRewardsIssuePost' {
            #$TestResult = Invoke-ReferralRockApiRewardsIssuePost -Authorization "TEST_VALUE" -ContentType "TEST_VALUE" -OverrideIneligible "TEST_VALUE" -Body "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ReferralRockApiRewardsPost' {
        It 'Test Invoke-ReferralRockApiRewardsPost' {
            #$TestResult = Invoke-ReferralRockApiRewardsPost -Authorization "TEST_VALUE" -ContentType "TEST_VALUE" -Body "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ReferralRockApiRewardsRemovePost' {
        It 'Test Invoke-ReferralRockApiRewardsRemovePost' {
            #$TestResult = Invoke-ReferralRockApiRewardsRemovePost -Authorization "TEST_VALUE" -ContentType "TEST_VALUE" -Body "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ReferralRockApiRewardsUpdatePost' {
        It 'Test Invoke-ReferralRockApiRewardsUpdatePost' {
            #$TestResult = Invoke-ReferralRockApiRewardsUpdatePost -Authorization "TEST_VALUE" -ContentType "TEST_VALUE" -Body "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
